version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: pnpm run dev
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PNPM_HOME=/app/.pnpm-store
      - CI=true

volumes:
  pnpm-store: